#!/bin/zsh
#  ----------------------------- setup -------------------------------
# cut and move to to .bashrc to load this file
# if [ -f ~/.zshrc_ext ]; then
#   . ~/.zshrc_ext
# fi

# Source common shell configurations
if [ -f "$HOME/.common_shell_config" ]; then
    source "$HOME/.common_shell_config"
fi

source "$HOME/.git-prompt.sh"

# ------------------------------ prompt (ZSH-specific) ------------------------------

setopt PROMPT_SUBST
precmd() { print -P "\n%F{yellow}%1~%f/" }
BRIGHT_WHITE='\e[97m'
PROMPT="  $winidx%F{white}(%n)%f %F{$BRIGHT_WHITE}%f%F{red}$(__git_ps1)%f --> %F{blue}%f "
