#!/bin/bash
#  ----------------------------- setup -------------------------------
# cut and move to to .bashrc to load this file
#if [ -f ~/.bashrc_ext ]; then
#   . ~/.bashrc_ext
#fi

# Source common shell configurations
if [ -f "$HOME/.common_shell_config" ]; then
    source "$HOME/.common_shell_config"
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

set -o vi
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=5000
HISTFILESIZE=10000
shopt -s checkwinsize


# ------------------------------- dircolors ------------------------------

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r "$HOME/.dircolors" && eval "$(dircolors -b ~/.dircolors)" 
    test -r "$HOME/.dircolors" && eval "$(dircolors -b)"
    alias grep='grep --color=auto'
    alias ls='ls --color=auto'
fi


# ------------------------------- colors -------------------------------

[ -n "${TMUX}" ] && winidx=$(tmux display-message -p '#I')

if (( winidx <0)); then
  winidx=""
fi

# ------------------------------ prompt ------------------------------

## set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;
esac
#${debian_chroot:+($debian_chroot)}
if [ "$color_prompt" = yes ]; then
	PS1='\n$winidx \[\033[01;37m\](\[\033[01;33m\]\u\033[01;37m\])
  \[\033[01;37m\]\W\[\033[00m\]/ \[\033[01;33m\] $(__git_ps1) \[\033[01;37m\]->> \[\033[00;37m\]  '
  else 
	PS1='\u@\h:\w\$ '
fi

# ------------------------------- completion -------------------------------

source "$HOME/.bash_git"

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

