# My Tmux settings
# change default meta key to same as screen

unbind C-a
set -g prefix C-a

bind-key L last-window
bind-key C-a last-window
set-option -g default-command zsh

unbind n
bind n new-window;

# vi for copy mode
setw -g mode-keys vi

# vi for command status
set -g status-keys vi
# form vim/tmux d/y buffer sync
set -g focus-events

# use a different prefix for nested
set-option -g history-limit 5000

# add double-tap meta key to toggle last window
set -g mouse on

# --- CLIPBOARD NOTIFICATIONS -----------------------------------
# When pressing 'y' in copy mode, copy and display a message
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy" \; display-message "Copied to macOS clipboard!"

# When dragging and releasing mouse, copy and display a message
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy" \; display-message "Copied to clipboard!"

# move to top
set -ga terminal-overrides ',*256color*:smcup@:rmcup@'

# create more intuitive split key combos (same as modern screen)
unbind |
bind | split-window -h
bind \\ split-window -h
bind 'C-\' split-window -h
unbind -
bind - split-window -v -p 50
unbind _
bind _ split-window -v -p 50
# Style the thin lines separating splits
# Make all division lines identical and highly visible
set -g pane-border-style "fg=cyan"
set -g pane-active-border-style "fg=cyan"

bind -r C-k resize-pane -U 4
bind -r C-j resize-pane -D 4
bind -r C-h resize-pane -L 4
bind -r C-l resize-pane -R 4

# vi keys to navigate panes
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# avoid cursor movement messing with resize
set -g repeat-time 200
set -g escape-time 50

set -g default-terminal "screen-256color"
set -g clock-mode-style 12
setw -g clock-mode-colour blue
set -g base-index 1
setw -g pane-base-index 1

# color of the window selection background
set -g mode-style "bg=#6ED9FF,fg=black"

# reload configuration
bind -r r source-file ~/.config/tmux/.tmux.conf

unbind s
bind s set-option status
set-option -g status-position top
set -g status-bg yellow
set -g status-fg black 
set -g status-interval 1
set -g status-left "%A, %B %-e, %Y, %-l:%M%P %Z%0z #(pomo)" 
set -g status-interval 1
set -g status-justify left
set -g status-left ""
set -g status-right ""
set -g status-right "#[fg=black] %m-%d-%Y %I:%M Learn_something_new "
set -g message-style "fg=cyan"
set -g status off
